{{ config(tags=["aws_usage", "daily"]) }}

WITH

STG AS (
  SELECT
    CONVERT_TIMEZONE('America/Chicago', _MODIFIED)                      :: TIMESTAMP_NTZ AS _MODIFIED_CENTRAL_TIME,
    CONVERT_TIMEZONE('America/Chicago', BILL_BILLING_PERIOD_START_DATE) :: TIMESTAMP_NTZ AS BILL_BILLING_PERIOD_START_DATE_CENTRAL_TIME,
    CONVERT_TIMEZONE('America/Chicago', BILL_BILLING_PERIOD_END_DATE)   :: TIMESTAMP_NTZ AS BILL_BILLING_PERIOD_END_DATE_CENTRAL_TIME,
    CONVERT_TIMEZONE('America/Chicago', LINE_ITEM_USAGE_START_DATE)     :: TIMESTAMP_NTZ AS LINE_ITEM_USAGE_START_DATE_CENTRAL_TIME,
    CONVERT_TIMEZONE('America/Chicago', LINE_ITEM_USAGE_END_DATE)       :: TIMESTAMP_NTZ AS LINE_ITEM_USAGE_END_DATE_CENTRAL_TIME,
    CONVERT_TIMEZONE('America/Chicago', _FIVETRAN_SYNCED)               :: TIMESTAMP_NTZ AS _FIVETRAN_SYNCED_CENTRAL_TIME,

		HASH(
			LINE_ITEM_RESOURCE_ID,
			IDENTITY_TIME_INTERVAL,
			LINE_ITEM_USAGE_TYPE,
			LINE_ITEM_USAGE_START_DATE
		) AS COMPUTED_ID,

    {{ 
      dbt_utils.star(
        from=source('aws_costs', 'HASHMAP_AWS_COSTS'),
        except=[
          "_MODIFIED",
          "BILL_BILLING_PERIOD_START_DATE",
          "BILL_BILLING_PERIOD_END_DATE",
          "LINE_ITEM_USAGE_START_DATE",
          "LINE_ITEM_USAGE_END_DATE",
          "_FIVETRAN_SYNCED"
        ]
      ) 
    }}
  FROM
    {{ source('aws_costs', 'HASHMAP_AWS_COSTS') }}
)

SELECT * FROM STG
 