WITH DAILY_USAGE AS (
  SELECT 
    SUM(CREDITS_USED)                   AS CREDITS_USED, 
    DATE_TRUNC('DAY', START_TIME)::DATE AS CALCULATED_ON 
  FROM 
    {{ ref('stg_hashmap_snowflake_usage') }} 
  GROUP BY 
    CALCULATED_ON 
  ORDER BY 
    CALCULATED_ON DESC
)

SELECT * FROM DAILY_USAGE