//=============================================================================
// create data resources
//=============================================================================
USE ROLE SYSADMIN;

// Databases
CREATE DATABASE RANDY_PITCHER_WORKSPACE_DEV;
CREATE DATABASE RANDY_PITCHER_WORKSPACE_TEST;
CREATE DATABASE RANDY_PITCHER_WORKSPACE_PROD;

// schemas
CREATE SCHEMA RANDY_PITCHER_WORKSPACE_PROD.ANALYTICS;
//=============================================================================


//=============================================================================
// create warehouses
//=============================================================================
USE ROLE SYSADMIN;

// dev warehouse
CREATE WAREHOUSE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH
  COMMENT='Warehouse for powering data engineering activities for the RANDY_PITCHER_WORKSPACE project'
  WAREHOUSE_SIZE=XSMALL
  AUTO_SUSPEND=60
  INITIALLY_SUSPENDED=TRUE;
//=============================================================================


//=============================================================================
// create object access (OA) roles
//=============================================================================
USE ROLE SECURITYADMIN;

// data access
CREATE ROLE RANDY_PITCHER_WORKSPACE_DEV_OWNER;
CREATE ROLE RANDY_PITCHER_WORKSPACE_DEV_WRITE;
CREATE ROLE RANDY_PITCHER_WORKSPACE_DEV_READ;
CREATE ROLE RANDY_PITCHER_WORKSPACE_TEST_OWNER;
CREATE ROLE RANDY_PITCHER_WORKSPACE_TEST_WRITE;
CREATE ROLE RANDY_PITCHER_WORKSPACE_TEST_READ;
CREATE ROLE RANDY_PITCHER_WORKSPACE_PROD_OWNER;
CREATE ROLE RANDY_PITCHER_WORKSPACE_PROD_WRITE;
CREATE ROLE RANDY_PITCHER_WORKSPACE_PROD_READ;
CREATE ROLE RANDY_PITCHER_WORKSPACE_PROD_ANALYTICS_READ;

// warehouse access
CREATE ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH_OWNER;
CREATE ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH_ALL_PRIVILEGES;

// grant all roles to sysadmin (always do this)
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEV_OWNER                   TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEV_WRITE                   TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEV_READ                    TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_TEST_OWNER                  TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_TEST_WRITE                  TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_TEST_READ                   TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_PROD_OWNER                  TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_PROD_WRITE                  TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_PROD_READ                   TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_PROD_ANALYTICS_READ         TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH_OWNER          TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH_ALL_PRIVILEGES TO ROLE SYSADMIN;
//=============================================================================
 

//=============================================================================
// grant privileges to object access roles
//=============================================================================
USE ROLE SECURITYADMIN;

// data access
GRANT OWNERSHIP ON DATABASE RANDY_PITCHER_WORKSPACE_DEV                                    TO ROLE RANDY_PITCHER_WORKSPACE_DEV_OWNER;
GRANT USAGE, CREATE SCHEMA ON DATABASE RANDY_PITCHER_WORKSPACE_DEV                         TO ROLE RANDY_PITCHER_WORKSPACE_DEV_WRITE;
GRANT USAGE ON DATABASE RANDY_PITCHER_WORKSPACE_DEV                                        TO ROLE RANDY_PITCHER_WORKSPACE_DEV_READ;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RANDY_PITCHER_WORKSPACE_DEV                      TO ROLE RANDY_PITCHER_WORKSPACE_DEV_READ;
GRANT OWNERSHIP ON DATABASE RANDY_PITCHER_WORKSPACE_TEST                                   TO ROLE RANDY_PITCHER_WORKSPACE_TEST_OWNER;
GRANT USAGE, CREATE SCHEMA ON DATABASE RANDY_PITCHER_WORKSPACE_TEST                        TO ROLE RANDY_PITCHER_WORKSPACE_TEST_WRITE;
GRANT USAGE ON DATABASE RANDY_PITCHER_WORKSPACE_TEST                                       TO ROLE RANDY_PITCHER_WORKSPACE_TEST_READ;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RANDY_PITCHER_WORKSPACE_TEST                     TO ROLE RANDY_PITCHER_WORKSPACE_TEST_READ;
GRANT OWNERSHIP ON DATABASE RANDY_PITCHER_WORKSPACE_PROD                                   TO ROLE RANDY_PITCHER_WORKSPACE_PROD_OWNER;
GRANT USAGE, CREATE SCHEMA ON DATABASE RANDY_PITCHER_WORKSPACE_PROD                        TO ROLE RANDY_PITCHER_WORKSPACE_PROD_WRITE;
GRANT OWNERSHIP ON SCHEMA RANDY_PITCHER_WORKSPACE_PROD.ANALYTICS                           TO ROLE RANDY_PITCHER_WORKSPACE_PROD_WRITE;
GRANT USAGE ON DATABASE RANDY_PITCHER_WORKSPACE_PROD                                       TO ROLE RANDY_PITCHER_WORKSPACE_PROD_READ;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RANDY_PITCHER_WORKSPACE_PROD                     TO ROLE RANDY_PITCHER_WORKSPACE_PROD_READ;
GRANT ROLE RANDY_PITCHER_WORKSPACE_PROD_ANALYTICS_READ                                     TO ROLE RANDY_PITCHER_WORKSPACE_PROD_READ;
GRANT USAGE ON DATABASE RANDY_PITCHER_WORKSPACE_PROD                                       TO ROLE RANDY_PITCHER_WORKSPACE_PROD_ANALYTICS_READ;
GRANT USAGE ON SCHEMA RANDY_PITCHER_WORKSPACE_PROD.ANALYTICS                               TO ROLE RANDY_PITCHER_WORKSPACE_PROD_ANALYTICS_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RANDY_PITCHER_WORKSPACE_PROD.ANALYTICS             TO ROLE RANDY_PITCHER_WORKSPACE_PROD_ANALYTICS_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA RANDY_PITCHER_WORKSPACE_PROD.ANALYTICS              TO ROLE RANDY_PITCHER_WORKSPACE_PROD_ANALYTICS_READ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA RANDY_PITCHER_WORKSPACE_PROD.ANALYTICS TO ROLE RANDY_PITCHER_WORKSPACE_PROD_ANALYTICS_READ;

// warehouse access
GRANT OWNERSHIP ON WAREHOUSE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH      TO ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH_OWNER;
GRANT ALL PRIVILEGES ON WAREHOUSE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH TO ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH_ALL_PRIVILEGES;
//=============================================================================


//=============================================================================
// create business function roles and grant access to object access roles
//=============================================================================
USE ROLE SECURITYADMIN;
 
// BF roles
CREATE ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
CREATE ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER;
 
// grant all roles to sysadmin (always do this)
GRANT ROLE RANDY_PITCHER_WORKSPACE_ADMIN     TO ROLE SYSADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER TO ROLE SYSADMIN;

// grant bf roles to admin roles
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;

// grant OA roles
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEV_OWNER                    TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEV_WRITE                    TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEV_READ                     TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_TEST_OWNER                   TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_TEST_WRITE                   TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_TEST_READ                    TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_PROD_OWNER                   TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_PROD_WRITE                   TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_PROD_READ                    TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_PROD_ANALYTICS_READ          TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH_OWNER           TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH_ALL_PRIVILEGES  TO ROLE RANDY_PITCHER_WORKSPACE_ADMIN;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEV_WRITE                    TO ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER;
GRANT ROLE RANDY_PITCHER_WORKSPACE_TEST_READ                    TO ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER;
GRANT ROLE RANDY_PITCHER_WORKSPACE_PROD_READ                    TO ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER;
GRANT ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER_WH_ALL_PRIVILEGES  TO ROLE RANDY_PITCHER_WORKSPACE_DEVELOPER;
GRANT ROLE FIVETRAN_READ_ROLE                                   TO ROLE RANDY_PITCHER_WORKSPACE_DEV;

// Grant pre-existing source read roles here
//=============================================================================