//=============================================================================
// delete everything in the project
//=============================================================================
USE ROLE SYSADMIN;
DROP DATABASE  CICD_DEMO_DEV;
DROP DATABASE  CICD_DEMO_TEST;
DROP DATABASE  CICD_DEMO_PROD;
DROP WAREHOUSE CICD_DEMO_DBT_TEST_WH;
DROP WAREHOUSE CICD_DEMO_DBT_PROD_WH;
DROP WAREHOUSE CICD_DEMO_SIGMA_ANALYST_WH;
DROP WAREHOUSE CICD_DEMO_TABLEAU_ANALYST_WH;
DROP WAREHOUSE CICD_DEMO_DEVELOPER_WH;

USE ROLE SECURITYADMIN;
DROP ROLE CICD_DEMO_DBT_TEST_WH_OWNER;
DROP ROLE CICD_DEMO_DBT_TEST_WH_USAGE;
DROP ROLE CICD_DEMO_DBT_TEST_SERVICE_ACCOUNT_ROLE;
DROP ROLE CICD_DEMO_DBT_PROD_WH_OWNER;
DROP ROLE CICD_DEMO_DBT_PROD_WH_USAGE;
DROP ROLE CICD_DEMO_DBT_PROD_SERVICE_ACCOUNT_ROLE;
DROP ROLE CICD_DEMO_SIGMA_ANALYST_WH_OWNER;
DROP ROLE CICD_DEMO_SIGMA_ANALYST_WH_USAGE;
DROP ROLE CICD_DEMO_SIGMA_ANALYST;
DROP ROLE CICD_DEMO_TABLEAU_ANALYST_WH_OWNER;
DROP ROLE CICD_DEMO_TABLEAU_ANALYST_WH_USAGE;
DROP ROLE CICD_DEMO_TABLEAU_ANALYST;
DROP ROLE CICD_DEMO_DEV_OWNER;
DROP ROLE CICD_DEMO_DEV_WRITE;
DROP ROLE CICD_DEMO_DEV_READ;
DROP ROLE CICD_DEMO_TEST_OWNER;
DROP ROLE CICD_DEMO_TEST_WRITE;
DROP ROLE CICD_DEMO_TEST_READ;
DROP ROLE CICD_DEMO_PROD_OWNER;
DROP ROLE CICD_DEMO_PROD_WRITE;
DROP ROLE CICD_DEMO_PROD_READ;
DROP ROLE CICD_DEMO_PROD_ANALYTICS_READ;
DROP ROLE CICD_DEMO_DEVELOPER_WH_OWNER;
DROP ROLE CICD_DEMO_DEVELOPER_WH_ALL_PRIVILEGES;
DROP ROLE CICD_DEMO_ADMIN;
DROP ROLE CICD_DEMO_DEVELOPER;
DROP USER CICD_DEMO_DBT_TEST_SERVICE_ACCOUNT_USER;
DROP USER CICD_DEMO_DBT_PROD_SERVICE_ACCOUNT_USER;
DROP USER CICD_DEMO_SIGMA_ANALYST_SERVICE_ACCOUNT_USER;
DROP USER CICD_DEMO_TABLEAU_ANALYST_SERVICE_ACCOUNT_USER;
//=============================================================================